sudo: required

services:
  - docker

jobs:
  include:
    - stage: test
      install: skip
      script:
        - make build
        - make test
    - stage: test-integration
        install: skip
        script:
          - make test-integration
